### ISSUE TITLE
Error while build and run Blazor: ILLink failed

### ISSUE THREAD

**Issue by marcbraun** [aesalazar/AsteroidsWasm#6]
Severity	Code	Description	Project	File	Line	Suppression State
Error		ILLink failed with exited code 1.	Asteroids.Blazor	C:\Users\Marc Braun\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets	204	

[Migration Report.pdf](https://github.com/aesalazar/AsteroidsWasm/files/4155234/Migration.Report.pdf)

**Comment by aesalazar** [comment]
How are you building it?  Why the need to migrate?  You need the latest Visual Studio 2019.4 in order to run blazor properly.  

Your report shows an error with the android project - do you have the VS android components installed (VS Installer)?
